pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.9-eclipse-temurin-21
    command: [cat]
    tty: true
  - name: buildah
    image: quay.io/buildah/stable
    command: [cat]
    tty: true
    securityContext:
      privileged: true
  - name: trivy
    image: aquasec/trivy:0.57.0
    command: [cat]
    tty: true
'''
        }
    }

    environment {
        APP_NAME       = 'java-spring'
        REGISTRY       = 'fmaulana24/devsecops'
        IMG_LATEST     = "${REGISTRY}:${APP_NAME}"
        IMG_BUILD      = "${REGISTRY}:${APP_NAME}-${BUILD_NUMBER}"
        SONAR_HOST_URL = 'http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000'
    }

    stages {
        stage('Unit Test') {
            steps {
                container('maven') {
                    dir('apps/java-spring/src') {
                        sh 'mvn test -q'
                    }
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'apps/java-spring/src/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                container('maven') {
                    withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                        dir('apps/java-spring/src') {
                            sh """
                                mvn sonar:sonar \
                                  -Dsonar.host.url=${SONAR_HOST_URL} \
                                  -Dsonar.token=${SONAR_TOKEN} \
                                  -Dsonar.projectKey=${APP_NAME} \
                                  -Dsonar.projectName=${APP_NAME} \
                                  -q
                            """
                        }
                    }
                }
            }
        }

        stage('Build Image') {
            steps {
                container('buildah') {
                    dir('apps/java-spring') {
                        sh "buildah build -t ${IMG_LATEST} -t ${IMG_BUILD} ."
                    }
                    sh "buildah push ${IMG_LATEST} docker-archive:image.tar"
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                container('trivy') {
                    sh """
                        trivy image \
                          --no-progress \
                          --exit-code 1 \
                          --severity HIGH,CRITICAL \
                          --ignore-unfixed \
                          --format table \
                          --output trivy-report.txt \
                          --input image.tar
                    """
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: 'trivy-report.txt', allowEmptyArchive: true
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                container('buildah') {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh 'buildah login -u "$DOCKER_USER" -p "$DOCKER_PASS" docker.io'
                        sh "buildah push ${IMG_LATEST} docker://docker.io/${IMG_LATEST}"
                        sh "buildah push ${IMG_BUILD} docker://docker.io/${IMG_BUILD}"
                    }
                }
            }
        }
    }

    post {
        always {
            container('buildah') {
                sh "buildah rmi ${IMG_LATEST} ${IMG_BUILD} || true"
            }
        }
    }
}
